# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - upgrade/*
  workflow_dispatch:
    inputs:
      debug:
        required: true
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: |
          echo "${{ inputs.debug }}"
          echo "${{ github.run_id }}-${{ github.run_attempt }}"
          echo "${{ github.repository }}"

      - name: Check debug
        if: inputs.debug == '' || inputs.debug == 'false'
        run: |
          echo "Debug is disabled"
